### ISSUE TITLE
Issue with V1.0.0

### ISSUE THREAD

**Issue by 5axes** [FormerLurker/ArcWelderPlugin#85]
I was working on the Cura PlugIn made by @fieldOfView. This weekend I have made some tests with the ArcWelder console. everything was running fine. Yesterday we have switch on your release 1.0.0 binary files. With the same files and the same options the result is different and much more worryingly, the result in NCViewer also appears to be invalid. 

Sample layer in Cura
![Layer_237_Cura](https://user-images.githubusercontent.com/11015345/100615905-91022280-3318-11eb-9aae-6f29b362cde4.JPG)
The GCode in NcViewer
![G01](https://user-images.githubusercontent.com/11015345/100616446-6795c680-3319-11eb-96ec-24cd9ca95a06.jpg)

Tested File in NCViewer with the fieldOfView binary ArcWelder.exe file
![tested](https://user-images.githubusercontent.com/11015345/100614608-ac6c2e00-3316-11eb-8c8e-6597a6c7f4e6.jpg)

The new result in NcViewer ...  (Not tested on the machine for the moment )
![Test_2](https://user-images.githubusercontent.com/11015345/100614617-af671e80-3316-11eb-956d-82cc32affbd1.jpg)

**Comment by 5axes** [comment]
Sample G01 File
[G01.txt](https://github.com/FormerLurker/ArcWelderPlugin/files/5616117/G01.txt)

Options in Cura
![options_cura](https://user-images.githubusercontent.com/11015345/100615426-e0941e80-3317-11eb-9684-48c18a7c952f.jpg)

Tested file on the machine  
[TestedCode.txt](https://github.com/FormerLurker/ArcWelderPlugin/files/5616132/TestedCode.txt)

New Gode issue from the release V1.0.0  ( I'm using the windows release)
[ResultV100.txt](https://github.com/FormerLurker/ArcWelderPlugin/files/5616134/ResultV100.txt)

**Comment by FormerLurker** [comment]
Will take a look, thanks for the report.

**Comment by FormerLurker** [comment]
Might be a false alarm.  It looks like a series of short arcs kills every viewer I've tried, even simplify 3d.  I have a program that simulates what marlin will do (the ArcStraightener). It replaces G2/G3 with G1 as the firmware would do (using the G2/G3 code from the prusa fork, slightly modified).  Here's the output gcode:

[inverse_output.txt](https://github.com/FormerLurker/ArcWelderPlugin/files/5616765/inverse_output.txt)

Here's what that looks like in simplify 3d:

![image](https://user-images.githubusercontent.com/33363128/100627164-4965a180-32ec-11eb-9268-b5f87ce8f3e1.png)

I'm not particularly happy that no viewers can properly handle G2/G3.  I've had more problems with this than the actual conversion algorithm.  This problem stumped me at first because I've NEVER seen simplify fail to properly render a gcode file.  After reviewing the first arc manually (ug....) everything looked fine, so that's why I thought to use the ArcStraightener.  Anyway, this is going to seriously confuse users, especially since it confused me!

**Comment by 5axes** [comment]
Well, I'm not so optimistic. I looked in another viewer and the result looks weird. The tested Gcode is fine in this viewer but the new one also has some flaws.   And it's strange that on these areas circular interpolations can  be so segmented as well.
![PreviousOne](https://user-images.githubusercontent.com/11015345/100637488-3aeea880-3333-11eb-945d-ecebe99f8b43.jpg)

![NewOne](https://user-images.githubusercontent.com/11015345/100637496-3d510280-3333-11eb-8e22-d5d9a50bf368.jpg)

And if we have a look to your inverted GCode In Cura we also have the small circular interpolation which are inverted in the area circled in black
![Inverted](https://user-images.githubusercontent.com/11015345/100639275-404cf280-3335-11eb-9d65-0e589c884907.JPG)

**Comment by FormerLurker** [comment]
I'm not sure what to trust here honestly.  I know that most viewers have issues, and I also know that the firmware interpolations look correct (down to the number of expected segments).  I will take another look and see if I can find any issues.  Your example looks like the top of a benchy, so I may just print one out with your settings.

Also, fyi (not that it's hurting anything in this case), but the maximum arc radius setting you have is way too low.  This should be on the order of at least 100 meters.  Shouldn't hurt anything, I just figured i'd point it out.

**Comment by FormerLurker** [comment]
Also, I'm not sure what you are pointing out in the second image.  Are you questioning why the 'arc' there isn't circular?  If so, it's because of the firmware compensation, and it appears to be doing what it was designed to do.  If you turn that off it will be on big circle.  Sorry if I'm misunderstanding you.

Edit:  Third image, not second, sorry.

**Comment by FormerLurker** [comment]
OK, I think I figured out what you were trying to illustrate on that third pic.  I plotted some of these arcs and did notice the endpoints were off a bit (I need to find a better tool for this, btw... if you know of any please let me know!).  I realized that the current_arc was getting aborted due to firmware compensation, but the underlying circle was being overwritten (a circle is calculated before an arc is generated), which resulted in some small deviations.  I think this is fixed.  The inverse processor wasn't showing this clearly (though it didn't look great obviously)because the very last segment is set to go to the endpoints (X and Y) of the G2/G3 statement, masking the underlying issue somewhat.

Here is the welded output now using the settings you have listed (except I bumped the min radius way up):

![image](https://user-images.githubusercontent.com/33363128/100644108-820f7600-3300-11eb-9051-0ca84914a89d.png)

That looks better.  Here's what the firmware will do assuming MM_PER_ARC_SEGMENT = 1 as the only option (using ArcStraightener.exe):

![image](https://user-images.githubusercontent.com/33363128/100644235-ae2af700-3300-11eb-895e-e13a30ed27c1.png)

That also looks much better.  Thanks for pointing this out and insisting you found what you did :)  The previous code that included firmware compensation actually handled this correctly, but I moved some code out of the arc generation routine into the segmented_arc class so I could track how many arcs were aborted.  In doing so I was allowing the currently tracked arc to update and wasn't swapping it back to the previous one.  Before the update this wasn't necessary because the arc wasn't created at all.  Very nice catch, thank you!

I just pushed a fix [you can find here](https://github.com/FormerLurker/ArcWelderLib/actions/runs/392124947).  Let me know if that fixes this for you.

**Comment by FormerLurker** [comment]
Oh, also, I'd like to drop an image of what would happen without firmware compensation (again, assuming only MM_PER_ARC_SEGMENT is set to 1.0):

![image](https://user-images.githubusercontent.com/33363128/100644955-9b64f200-3301-11eb-8117-6810a580c9e8.png)

So, at least for this model it looks like the firmware compensation is doing what it supposed to now :)

**Comment by FormerLurker** [comment]
I patched the release and updated the artifacts minus the raspberry pi binary, which I will add soon.  Thanks for testing and for your report!

**Comment by 5axes** [comment]
Looks better now , even in NCViewer
![NewRelease](https://user-images.githubusercontent.com/11015345/100649438-bdcb2f80-3342-11eb-9f67-0d7d77d3d115.JPG)

Some tests will be made on the machine. 
But I still don't understand why with the friday console application release  , with the same parameter the number of arc were lower than  the result we got now ?  The new parameter were already used in this case and during my tests the smallest radius was split into small circular interpolation but nor the 2 biggest circle 
![Compare](https://user-images.githubusercontent.com/11015345/100651917-8068a100-3346-11eb-9490-dffc6bddb60d.jpg)
G1 
[WallInner_WallOuter.txt](https://github.com/FormerLurker/ArcWelderPlugin/files/5618149/WallInner_WallOuter.txt)
Result tested on machine 
[TestedCodeWallInner_WallOuter.txt](https://github.com/FormerLurker/ArcWelderPlugin/files/5618150/TestedCodeWallInner_WallOuter.txt)
Present result
[NowWallInner_WallOuter.txt](https://github.com/FormerLurker/ArcWelderPlugin/files/5618151/NowWallInner_WallOuter.txt)

**Comment by 5axes** [comment]
Ok tests on machine are OK, I can close the Issue.  On my machine (Ender 3 with Marlin) these test shows that options mm_per_arc_segment and min_arc_segment is a must have. The lower part was made without this option and small Arcs doesn't have the right shape at all.
![20201130_234750](https://user-images.githubusercontent.com/11015345/100676814-e9addb80-3369-11eb-8885-d8972636375f.jpg)

**Comment by FormerLurker** [comment]
Thank you!  I am v glad, since I don't have this issue and can't test it well (using custom firmware).  Amazing feedback, but the testing is where I really need help.

**Comment by FormerLurker** [comment]
Oh, and btw, that pic is GREAT.  Can I steal it and use it as an example image in the docs?

**Comment by 5axes** [comment]
No problem , feel free  to use it for your documentation

**Comment by FormerLurker** [comment]
Oh, I didn't answer your last question:

> But I still don't understand why with the friday console application release , with the same parameter the number of arc were lower than the result we got now ? The new parameter were already used in this case and during my tests the smallest radius was split into small circular interpolation but nor the 2 biggest circle

I will look into this.  My instincts tell me that it it because the new process correctly swaps out the current arc, but I will verify.
